language: python
python:
  - "3.6.1"
install:
  - pip install coveralls
script:
  - coverage run tests.py
after_success:
  - coveralls
addons:
  code_climate:
    repo_token: 4e18f07d0ee7c5a002b8a48b19f0e0860399932c9f8dc70cfbe555599b53a63c
env:
  - PYTHONPATH=`pwd`